# Reading df

In [1]:
import pandas as pd
import numpy as np

In [2]:
fifa21 = pd.read_csv('fifa21_train.csv')

pd.set_option('display.max_columns', None)

print(fifa21.shape)
fifa21.head(3)

(11701, 101)


ID           Name  Age  Nationality                     Club   BP  \
0  184383      A. Pasche   26  Switzerland        FC Lausanne-Sport   CM   
1  188044  Alan Carvalho   30     China PR  Beijing Sinobo Guoan FC   ST   
2  184431    S. Giovinco   33        Italy                 Al Hilal  CAM   

   Position                               Team & Contract Height  Weight  \
0    CM CDM                 FC Lausanne-Sport 2015 ~ 2020   5'9"  161lbs   
1  ST LW LM  Beijing Sinobo Guoan FC Dec 31, 2020 On Loan   6'0"  159lbs   
2    CAM CF                          Al Hilal 2019 ~ 2022   5'4"  134lbs   

    foot  Growth        Joined Loan Date End  Value  Wage Release Clause  \
0  Right       1   Jul 1, 2015           NaN  €525K   €4K          €801K   
1  Right       0  Jan 16, 2015  Dec 31, 2020  €8.5M  €23K             €0   
2  Right       0  Jan 31, 2019           NaN    €9M  €49K         €15.3M   

               Contract  Attacking  Crossing  Finishing  Heading Accuracy  \
0           2015 ~ 2020        258        54         47                43   
1  Dec 31, 2020 On Loan        365        66         79                76   
2           2019 ~ 2022        336        73         76                34   

   Short Passing  Volleys  Skill  Dribbling  Curve  FK Accuracy  Long Passing  \
0             70     44.0    286         61   44.0           55            63   
1             68     76.0    375         83   78.0           72            63   
2             78     75.0    424         85   89.0           91            74   

   Ball Control  Movement  Acceleration  Sprint Speed  Agility  Reactions  \
0            63       346            64            73     61.0         66   
1            79       404            83            83     88.0         75   
2            85       424            84            76     93.0         78   

   Balance  Power  Shot Power  Jumping  Stamina  Strength  Long Shots  \
0     82.0    306          62     73.0       71        55          45   
1     75.0    372          74     81.0       75        74          68   
2     93.0    308          79     34.0       75        42          78   

   Mentality  Aggression  Interceptions  Positioning  Vision  Penalties  \
0        290          54           52.0         62.0    68.0         54   
1        313          54           33.0         78.0    72.0         76   
2        332          75           26.0         80.0    78.0         73   

   Composure  Defending  Marking  Standing Tackle  Sliding Tackle  \
0       54.0        148       49               56            43.0   
1       70.0         77       35               20            22.0   
2       82.0         80       23               29            28.0   

   Goalkeeping  GK Diving  GK Handling  GK Kicking  GK Positioning  \
0           48          7           12          14               9   
1           55         11            7          14               7   
2           21          6            3           6               3   

   GK Reflexes  Total Stats  Base Stats  W/F  SM   A/W     D/W   IR  PAC  SHO  \
0            6         1682         357  4 ★  2★  High  Medium  1 ★   69   51   
1           16         1961         412  3 ★  4★  High     Low  2 ★   83   75   
2            3         1925         404  4 ★  4★  High  Medium  2 ★   80   77   

   PAS  DRI  DEF  PHY Hits    LS    ST    RS    LW    LF    CF    RF    RW  \
0   63   63   51   60    3  58+1  58+1  58+1  61+0  62+0  62+0  62+0  61+0   
1   68   82   33   71   44  77+0  77+0  77+0  77+0  77+0  77+0  77+0  77+0   
2   78   86   27   56   73  73+2  73+2  73+2  80+0  79+0  79+0  79+0  80+0   

    LAM   CAM   RAM    LM   LCM    CM   RCM    RM   LWB   LDM   CDM   RDM  \
0  63+1  63+1  63+1  63+1  63+1  63+1  63+1  63+1  59+1  59+1  59+1  59+1   
1  76+1  76+1  76+1  76+1  68+2  68+2  68+2  76+1  57+2  53+2  53+2  53+2   
2  80+0  80+0  80+0  79+1  74+2  74+2  74+2  79+1  59+2  56+2  56+2  56+2   

    RWB    LB   LCB    CB   RCB    RB    GK  OVA  

# Standardizing header

In [3]:
col1 = list(map(lambda el : el.lower(),fifa21))
fifa21.columns = col1

col = fifa21.columns.str.replace(" ","_")
fifa21.columns = col

fifa21.columns

Index(['id', 'name', 'age', 'nationality', 'club', 'bp', 'position',
       'team_&_contract', 'height', 'weight',
       ...
       'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb', 'gk', 'ova'],
      dtype='object', length=101)

# Data Cleaning

### Dropping first columns with unique values

In [4]:
fifa21 = fifa21.drop(['id', 'name'], axis=1)

### Checking for columns that are the sum of others and dropping them

ls-gk --> data about best fit position, but we also have it in the bp column so we choose to drop them

goalkeeper = gk_driving - gk_reflexes

defending = marking - sliding_tackle

mentality = aggression - penalties

power = shot_power - long_shots

movement = acceleration - balance

skill = dribbling - ball_control

attacking = crossing - volleys

base_stats = pac-phy

In [5]:
def dropping_cols(df,indexes1,indexes2):
   
    for i in range (len(indexes1)):
        cols = list(df.columns)
        min_index = cols.index(indexes1[i])
        max_index = cols.index(indexes2[i])
        df = df.drop(cols[min_index:max_index+1],axis=1)
    return df

In [6]:
first = ['ls','gk_diving','marking','aggression','shot_power','acceleration','dribbling','crossing','pac']
last = ['gk','gk_reflexes','sliding_tackle','penalties','long_shots','balance','ball_control','volleys','phy']
fifa21 = dropping_cols(fifa21,first,last)

### Adjusting weight and height

In [7]:
col = fifa21['weight'].str.replace("lbs","")
fifa21['weight'] = col
fifa21['weight'] = pd.to_numeric(fifa21['weight'], errors='coerce')

In [8]:
fifa21['height'] = fifa21['height'].str.replace("'", '+')
fifa21['height'] = fifa21['height'].str.replace('"', '/12')
fifa21['height'] = round(fifa21['height'].apply(eval),2)

### Checking columns that must be numerical but are categorical and dealing with them

Removing € , M , K

In [9]:
def replace_K (df, column):
    for col in column:
        df[col] = df[col].str.replace('€','').str.replace('K','*1000').str.replace('M','*1000000').apply(eval)
    return df

In [10]:
fifa21 = replace_K(fifa21, ['value','wage','release_clause','hits'])

Removing ★

In [11]:
def replace_stars(df, column):
    for col in column:
        df[col] = pd.to_numeric((df[col].str.replace('★','')), errors='coerce')
    return df

In [12]:
stars = ['w/f','sm', 'ir']
fifa21 = replace_stars(fifa21, stars)

### Dropping redundant values or that give us less information due to its excess of uniques

In [13]:
print(len(fifa21['nationality'].unique()))
print(len(fifa21['club'].unique()))
print(len(fifa21['position'].unique()))
print(len(fifa21['joined'].unique()))

159
886
544
1690


In [14]:
fifa21 = fifa21.drop(fifa21[['position','joined', 'nationality', 'club']],axis=1)

### Changing columns that have categorical values easy convertibles to numeric

In [15]:
fifa21['a/w'] = pd.to_numeric((fifa21['a/w'].replace({'Low': '1', 'Medium' : '2', 'High':'3'})),errors='coerce')
fifa21['d/w'] = pd.to_numeric((fifa21['d/w'].replace({'Low': '1', 'Medium' : '2', 'High':'3'})),errors='coerce')

In [16]:
# def labeling(column,old_names,labeling):
#     labels = list(range(labeling[0],len(old_names)+1,labeling[1]))
#     for i in range(len(old_names)):
#         column = column.str.replace(old_names[i],str(labels[i]))
#     column = pd.to_numeric(column)
#     return column

In [17]:
# change_names = ['Low','Medium','High']

# fifa21['a/w'] = labeling(fifa21['a/w'],change_names,[1,1])
# fifa21['d/w'] = labeling(fifa21['d/w'],change_names,[1,1])

### Checking for NaN and strange values and dealing with them (also dropping redundat columns)

In [18]:
fifa21[fifa21['wage']==0]

age  bp          team_&_contract  height  weight   foot  growth  \
32      25  CB           Puebla FC 2007    6.00     168  Right       3   
44      33  CM  New York Red Bulls 2009    5.83     157  Right       4   
102     38  ST         Ivory Coast Free    6.17     176  Right       0   
105     32  LB             Bolivia Free    5.67     154   Left       0   
137     32  RB               Chile Free    5.75     165  Right       0   
...    ...  ..                      ...     ...     ...    ...     ...   
11648   23  GK        South Africa Free    6.08     165  Right       8   
11650   36  ST      Czech Republic Free    6.67     234  Right       2   
11679   32  CB              Mexico Free    6.00     176   Left       0   
11680   30  ST                Peru Free    6.08     181  Right       0   
11699   26  CM            Barnsley 2010    6.17     179  Right       7   

      loan_date_end  value  wage  release_clause             contract  \
32              NaN    0.0     0             0.0                 2007   
44              NaN    0.0     0             0.0                 2009   
102             NaN    0.0     0             0.0     Ivory Coast Free   
105             NaN    0.0     0             0.0                 Free   
137             NaN    0.0     0             0.0                 Free   
...             ...    ...   ...             ...                  ...   
11648           NaN    0.0     0             0.0                 Free   
11650           NaN    0.0     0             0.0  Czech Republic Free   
11679           NaN    0.0     0             0.0                 Free   
11680           NaN    0.0     0             0.0                 Free   
11699           NaN    0.0     0             0.0                 2010   

       attacking  skill  movement  power  mentality  composure  defending  \
32           151    154       188    151        190        NaN        125   
44           271    293       189    294        298        NaN        139   
102          370    376       327    388        363       80.0         83   
105          234    247       344    287        222       57.0        203   
137          310    362       390    345        355       76.0        221   
...          ...    ...       ...    ...        ...        ...        ...   
11648        142    162       228    188        122       51.0         79   
11650        302    220       208    324        302        NaN         65   
11679        319    268       320    316        321       75.0        237   
11680        376    320       335    358        330        NaN         71   
11699        254    284       198    258        241        NaN        113   

       goalkeeping  total_stats  base_stats  w/f  sm  a/w  d/w  ir  hits  ova  
32              68         1027         285    2   1  NaN  NaN   1   4.0   60  
44              71         1555         420    4   1  NaN  NaN   2   4.0   76  
102             49         1956         401    4   3  2.0  1.0   3  20.0   81  
105             63         1600         346    3   2  3.0  2.0   1  17.0   69  
137             36         2019         424    3   3  3.0  2.0   2  13.0   76  
...            ...          ...         ...  ...  ..  ...  ...  ..   ...  ...  
11648          349         1270         399    3   1  2.0  2.0   1   3.0   68  
11650          159         1580         401    3   1  NaN  NaN   3   3.0   78  
11679           60         1841         384    3   2  2.0  2.0   3  46.0   77  
11680           48         1838         392    4   3  2.0  1.0   3   6.0   78  
11699           81         1429         400    3   1  NaN  NaN   3   3.0   68  

[300 rows x 29 columns]

In [19]:
fifa21 = fifa21[fifa21['wage']>0]

In [20]:
fifa21.isna().sum()

age                    0
bp                     0
team_&_contract        0
height                 0
weight                 0
foot                   0
growth                 0
loan_date_end      10772
value                  0
wage                   0
release_clause         0
contract               0
attacking              0
skill                  0
movement               0
power                  0
mentality              0
composure            211
defending              0
goalkeeping            0
total_stats            0
base_stats             0
w/f                    0
sm                     0
a/w                    0
d/w                    0
ir                     0
hits                   0
ova                    0
dtype: int64

In [21]:
fifa21 = fifa21.drop(['loan_date_end','team_&_contract','contract'], axis=1)
fifa21 = fifa21.dropna()

### Checking for high correlations between columns

In [22]:
X_corr = fifa21.drop(['ova'],axis=1)

X_num_corr = X_corr.select_dtypes(np.number)

In [23]:
for X_col1 in X_num_corr:
    for X_col2 in X_num_corr:
        corr = X_num_corr[X_col1].corr(X_num_corr[X_col2])
        if (abs(corr)>0.9) & (X_col1 != X_col2):
            print('Variables '+ X_num_corr[X_col1].name + ' and ' + X_num_corr[X_col2].name +' corr = ' + str(corr))

Variables value and release_clause corr = 0.9802833055930668
Variables release_clause and value corr = 0.9802833055930668
Variables attacking and skill corr = 0.9287777160246724
Variables attacking and total_stats corr = 0.9045009248200863
Variables skill and attacking corr = 0.9287777160246724
Variables skill and total_stats corr = 0.9296130903783199
Variables mentality and total_stats corr = 0.9490913375367086
Variables total_stats and attacking corr = 0.9045009248200864
Variables total_stats and skill corr = 0.92961309037832
Variables total_stats and mentality corr = 0.9490913375367087


### Removing columns with high correlation that are redundant

In [24]:
fifa21 = fifa21.drop(['total_stats','release_clause','attacking'],axis=1)
fifa21.shape

(11190, 23)

# X y Split

In [25]:
y = fifa21['ova']
X = fifa21.drop(['ova'],axis=1)

X_num = X.select_dtypes(np.number)
X_cat = X.select_dtypes(object)

### Normalize numeric values

In [26]:
from sklearn.preprocessing import MinMaxScaler

In [27]:
MinMaxtransformer = MinMaxScaler().fit(X_num)
X_normalized = MinMaxtransformer.transform(X_num)
X_normalized = pd.DataFrame(X_normalized,columns=X_num.columns)
X_normalized.head()

age    height    weight    growth     value      wage     skill  \
0  0.370370  0.401198  0.349206  0.038462  0.005833  0.006256  0.569087   
1  0.518519  0.550898  0.333333  0.000000  0.094444  0.040214  0.777518   
2  0.629630  0.149701  0.134921  0.000000  0.100000  0.086685  0.892272   
3  0.222222  0.449102  0.277778  0.500000  0.003056  0.006256  0.505855   
4  0.259259  0.502994  0.261905  0.307692  0.008056  0.002681  0.555035   

   movement     power  mentality  composure  defending  goalkeeping  \
0  0.663818  0.556270   0.654596   0.500000   0.518219     0.084309   
1  0.829060  0.768489   0.718663   0.690476   0.230769     0.100703   
2  0.886040  0.562701   0.771588   0.833333   0.242915     0.021077   
3  0.481481  0.463023   0.562674   0.428571   0.599190     0.070258   
4  0.601140  0.472669   0.665738   0.547619   0.668016     0.093677   

   base_stats   w/f    sm  a/w  d/w    ir      hits  
0    0.492366  0.75  0.25  1.0  0.5  0.00  0.000000  
1    0.702290  0.50  0.75  1.0  0.0  0.25  0.004458  
2    0.671756  0.75  0.75  1.0  0.5  0.25  0.007611  
3    0.385496  0.25  0.25  0.5  0.5  0.00  0.000435  
4    0.503817  0.25  0.50  0.0  0.5  0.00  0.000109

### Encode categorical values and concat new_X

In [28]:
from sklearn.preprocessing import OneHotEncoder

In [29]:
def one_hot_encoder(col):
    col_df = pd.DataFrame(col)
    one_hot = OneHotEncoder(drop='first').fit(col_df)
    encoded_array = one_hot.transform(col_df).toarray()
    print(encoded_array)
    col_names = col.unique()
    col_names = np.delete(col_names, [0])
    print(col_names)
    df_encoded = pd.DataFrame(encoded_array, columns=col_names)
    return df_encoded

In [30]:
new_X = X_normalized

for name in X_cat.columns:
    encoded_X = one_hot_encoder(X_cat[name])
    new_X = pd.concat([new_X, encoded_X], axis=1)

new_X

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['ST' 'CAM' 'CDM' 'LM' 'RB' 'CB' 'RM' 'GK' 'LB' 'RW' 'LWB' 'LW' 'RWB' 'CF']
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [0.]]
['Left']


age    height    weight    growth     value      wage     skill  \
0      0.370370  0.401198  0.349206  0.038462  0.005833  0.006256  0.569087   
1      0.518519  0.550898  0.333333  0.000000  0.094444  0.040214  0.777518   
2      0.629630  0.149701  0.134921  0.000000  0.100000  0.086685  0.892272   
3      0.222222  0.449102  0.277778  0.500000  0.003056  0.006256  0.505855   
4      0.259259  0.502994  0.261905  0.307692  0.008056  0.002681  0.555035   
...         ...       ...       ...       ...       ...       ...       ...   
11185  0.481481  0.299401  0.293651  0.000000  0.006111  0.000000  0.562061   
11186  0.333333  0.598802  0.404762  0.192308  0.006944  0.004468  0.480094   
11187  0.407407  0.598802  0.452381  0.153846  0.017778  0.006256  0.124122   
11188  0.222222  0.251497  0.206349  0.307692  0.012222  0.002681  0.580796   
11189  0.222222  0.299401  0.206349  0.346154  0.007778  0.002681  0.524590   

       movement     power  mentality  composure  defending  goalkeeping  \
0      0.663818  0.556270   0.654596   0.500000   0.518219     0.084309   
1      0.829060  0.768489   0.718663   0.690476   0.230769     0.100703   
2      0.886040  0.562701   0.771588   0.833333   0.242915     0.021077   
3      0.481481  0.463023   0.562674   0.428571   0.599190     0.070258   
4      0.601140  0.472669   0.665738   0.547619   0.668016     0.093677   
...         ...       ...        ...        ...        ...          ...   
11185  0.726496  0.546624   0.554318   0.571429   0.242915     0.112412   
11186  0.626781  0.450161   0.587744   0.404762   0.663968     0.114754   
11187  0.353276  0.270096   0.128134   0.523810   0.085020     0.784543   
11188  0.783476  0.466238   0.518106   0.547619   0.170040     0.105386   
11189  0.792023  0.575563   0.526462   0.523810   0.145749     0.084309   

       base_stats   w/f    sm  a/w  d/w    ir      hits   ST  CAM  CDM   LM  \
0        0.492366  0.75  0.25  1.0  0.5  0.00  0.000000  0.0  0.0  0.0  1.0   
1        0.702290  0.50  0.75  1.0  0.0  0.25  0.004458  0.0  0.0  0.0  0.0   
2        0.671756  0.75  0.75  1.0  0.5  0.25  0.007611  0.0  0.0  0.0  0.0   
3        0.385496  0.25  0.25  0.5  0.5  0.00  0.000435  0.0  1.0  0.0  0.0   
4        0.503817  0.25  0.50  0.0  0.5  0.00  0.000109  0.0  1.0  0.0  0.0   
...           ...   ...   ...  ...  ...   ...       ...  ...  ...  ...  ...   
11185    0.416031  0.50  0.50  1.0  0.0  0.00  0.000109  0.0  0.0  0.0  0.0   
11186    0.454198  0.50  0.25  0.5  0.5  0.00  0.000000  0.0  0.0  0.0  0.0   
11187    0.606870  0.25  0.00  0.5  0.5  0.00  0.000000  0.0  0.0  0.0  0.0   
11188    0.416031  0.50  0.50  1.0  0.5  0.00  0.000326  0.0  0.0  0.0  0.0   
11189    0.412214  0.50  0.50  1.0  0.0  0.00  0.000544  0.0  0.0  0.0  0.0   

        RB   CB   RM   GK   LB   RW  LWB   LW  RWB   CF  Left  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   1.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  
11185  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   1.0  
11186  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  
11187  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   1.0  
11188  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   1.0  
11189  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0  

[11190 rows x 35 columns]

# Train-test split

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8952, 35)
(2238, 35)
(8952,)
(2238,)


# Train/fit our model

In [33]:
from sklearn import linear_model

In [34]:
lm = linear_model.LinearRegression()
print(lm.fit(X_train,y_train))

LinearRegression()


# Testing our model

In [35]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [41]:
predictions_train = lm.predict(X_train)
print(round(r2_score(y_train, predictions_train),2))

0.87


In [42]:
predictions_test = lm.predict(X_test)
print(round(r2_score(y_test, predictions_test),2))

0.88


In [44]:
mse = mean_squared_error(y_test,predictions_test)
rmse = np.sqrt(mean_squared_error(y_test,predictions_test))

print(round(mse,2))
print(round(rmse,2))

5.68
2.38


In [45]:
print(round(mean_absolute_error(y_train,predictions_train),2))
print(round(mean_absolute_error(y_test,predictions_test),2))

1.9
1.88


In [46]:
def cleaner (df):
    
    # Standardizing header
    col1 = list(map(lambda el : el.lower(),df))
    df.columns = col1
    col = df.columns.str.replace(" ","_")
    df.columns = col
    
    ### Dropping first columns with unique values
    df = df.drop(['id', 'name'], axis=1)
    
    ### Dropping columns that are sum of others
    first = ['ls','gk_diving','marking','aggression','shot_power','acceleration','dribbling','crossing','pac']
    last = ['gk','gk_reflexes','sliding_tackle','penalties','long_shots','balance','ball_control','volleys','phy']
    df = dropping_cols(df,first,last)
    
    ### Adjusting weight and height
    col = df['weight'].str.replace("lbs","")
    df['weight'] = col
    df['weight'] = pd.to_numeric(df['weight'], errors='coerce')
    
    df['height'] = df['height'].str.replace("'", '+')
    df['height'] = df['height'].str.replace('"', '/12')
    df['height'] = round(df['height'].apply(eval),2)
    
    ###Removing € , M , K
    df = replace_K(df, ['value','wage','release_clause','hits'])
    
    ###Removing ★
    stars = ['w/f','sm', 'ir']
    df = replace_stars(df, stars)
    
    ### Dropping redundant values or that give us less information due to its excess of uniques
    df = df.drop(df[['position','joined', 'nationality', 'club']],axis=1)
    
    ### Changing columns that have categorical values easy convertibles to numeric
    df['a/w'] = pd.to_numeric((df['a/w'].replace({'Low': '1', 'Medium' : '2', 'High':'3'})),errors='coerce')
    df['d/w'] = pd.to_numeric((df['d/w'].replace({'Low': '1', 'Medium' : '2', 'High':'3'})),errors='coerce')
    
    ### Checking for NaN and strange values and dropping redundat columns
    df = df[df['wage']>0]
    df = df.drop(['loan_date_end','team_&_contract','contract'], axis=1)
    df = df.dropna()
    
    ### Removing columns with high correlation that are redundant
    df = df.drop(['total_stats','release_clause','attacking'],axis=1)
    
    ### X y Split
    y = df['ova']
    X = df.drop(['ova'],axis=1)

    X_num = X.select_dtypes(np.number)
    X_cat = X.select_dtypes(object)
    
    ### Normalize numeric values
    MinMaxtransformer = MinMaxScaler().fit(X_num)
    X_normalized = MinMaxtransformer.transform(X_num)
    X_normalized = pd.DataFrame(X_normalized,columns=X_num.columns)
    X_normalized.head()
    
    ### Encode categorical values and concat new_X
    new_X = X_normalized

    for name in X_cat.columns:
        encoded_X = one_hot_encoder(X_cat[name])
        new_X = pd.concat([new_X, encoded_X], axis=1)

    return new_X,y    
    

In [47]:
new_test_df = pd.read_csv('fifa21_validate.csv')

pd.set_option('display.max_columns', None)

print(new_test_df.shape)

(1999, 101)


In [48]:
new_X_test,new_y_test = cleaner(new_test_df)
print(new_X_test.shape)
print(new_y_test.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['CAM' 'GK' 'CDM' 'RM' 'RB' 'CM' 'LB' 'LM' 'ST' 'RWB' 'LW' 'LWB' 'RW' 'CF']
[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [1.]
 [1.]]
['Left']
(1920, 35)
(1920,)


In [49]:
new_predictions_test = lm.predict(new_X_test)
print(round(r2_score(new_y_test, new_predictions_test),2))

0.79


C:\Users\julia\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- CM
Feature names seen at fit time, yet now missing:
- CB

  warnings.warn(message, FutureWarning)


In [50]:
new_mse = mean_squared_error(new_y_test,new_predictions_test)
new_rmse = np.sqrt(mean_squared_error(new_y_test,new_predictions_test))

print(round(new_mse,2))
print(round(new_rmse,2))

9.73
3.12
